SELECT
    o.O_ORDERKEY AS ORDER_KEY
    , o.O_CUSTKEY AS CUSTOMER_KEY
    , o.O_ORDERDATE AS ORDER_DATE
    , DATEADD(DAY, 5, o.O_ORDERDATE) AS SHIPMENT_DATE
    , TO_NUMBER(RPAD(CONCAT(o.O_ORDERKEY, o.O_CUSTKEY, TO_CHAR(o.O_ORDERDATE, 'YYYYMMDD')),  24, '0')) AS SHIPMENT_NUMBER
    , o.O_TOTALPRICE AS AMOUNT
FROM {{ source('tpch_sample', 'ORDERS') }} AS o
WHERE O_ORDERDATE = TO_DATE('{{ var('load_date') }}')
