SELECT
  O_ORDERKEY AS ORDER_KEY
  , O_CUSTKEY AS CUSTOMER_KEY
  , O_ORDERSTATUS AS ORDER_STATUS
  , O_TOTALPRICE AS TOTAL_PRICE
  , O_ORDERDATE AS ORDER_DATE
  , O_ORDERPRIORITY AS ORDER_PRIORITY
  , O_CLERK AS CLERK
  , O_SHIPPRIORITY AS SHIP_PRIORITY
  , O_COMMENT AS COMMENT
  , C_NAME AS CUSTOMER_NAME
  , C_ADDRESS AS CUSTOMER_ADDRESS
  , C_NATIONKEY AS CUSTOMER_NATION_KEY
  , C_PHONE AS CUSTOMER_PHONE
  , C_ACCTBAL AS CUSTOMER_ACCT_BAL
  , C_MKTSEGMENT AS CUSTOMER_MKT_SEGMENT
  , C_COMMENT AS CUSTOMER_COMMENT
FROM {{ source('tpch_sample', 'ORDERS') }} AS o
LEFT JOIN {{ source('tpch_sample', 'CUSTOMER') }} AS c
ON o.O_CUSTKEY = c.C_CUSTKEY
WHERE O_ORDERDATE = TO_DATE('{{ var('load_date') }}')
