SELECT
  O_ORDERKEY AS ORDER_KEY
  , O_CUSTKEY AS CUSTOMER_KEY
  , O_ORDERSTATUS AS ORDER_STATUS
  , O_TOTALPRICE AS TOTAL_PRICE
  , O_ORDERDATE AS ORDER_DATE
  , O_ORDERPRIORITY AS ORDER_PRIORITY
  , O_CLERK AS CLERK
  , O_SHIPPRIORITY AS SHIP_PRIORITY
  , O_COMMENT AS COMMENT
FROM {{ source('tpch_sample', 'ORDERS') }}
WHERE O_ORDERDATE = TO_DATE('{{ var('load_date') }}')
