SELECT
  C_CUSTKEY AS CUSTOMER_KEY
  , C_NAME AS NAME
  , C_ADDRESS AS ADDRESS
  , C_NATIONKEY AS NATION_KEY
  , C_PHONE AS PHONE
  , C_ACCTBAL AS ACCT_BAL
  , C_MKTSEGMENT AS MKT_SEGMENT
  , C_COMMENT AS COMMENT
FROM {{ source('tpch_sample', 'CUSTOMER') }}
